[plugin]
name = "yucky-ewwii"
build = "cargo build --release"
artifact = "target/release/libyucky-ewwii.so"

[plugin.prebuilt]
url = "https://github.com/Ewwii-sh/yucky-ewwii/releases/download/{version}/libyucky_ewwii.so"
